services:
  opencode:
    build:
      context: .
      dockerfile: docker/opencode/Dockerfile
    image: horizon-sdlc/opencode:latest
    container_name: horizon-opencode
    
    # Environment variables
    environment:
      # Required: AI Provider API Key
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}

      # Optional: GitHub integration
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}

      # Optional: Magic MCP Server (21st.dev)
      - TWENTY_FIRST_API_KEY=${TWENTY_FIRST_API_KEY:-}

      # Terraform Cloud integration (READ-ONLY)
      - TF_CLOUD_TOKEN=${TF_CLOUD_TOKEN:-}

      # Google Cloud Platform credentials (READ-ONLY)
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-}

      # Container configuration
      - NODE_ENV=production
      - WORKSPACE_DIR=/workspace
      
      # MCP Server configuration
      - MCP_SERVER_TIMEOUT=30000
      - MCP_SERVER_RETRIES=3
      
      # Security settings
      - SECURE_MODE=true
      - LOG_LEVEL=info
    
    # Volume mounts
    volumes:
      # Mount current workspace to container workspace
      - type: bind
        source: .
        target: /workspace
      
      # Optional: Mount Docker socket for container management (if needed)
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    
    # Port mappings (if OpenCode exposes any ports)
    ports:
      - "3000:3000"  # OpenCode web interface (if available)
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Health check - disabled for interactive OpenCode
    # healthcheck:
    #   test: ["CMD", "/usr/local/bin/healthcheck.sh"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s
    
    # Restart policy
    restart: unless-stopped
    
    # Network configuration
    networks:
      - opencode-network
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # User configuration (run as non-root if possible)
    # user: "1000:1000"  # Uncomment and adjust if needed
    
    # Working directory
    working_dir: /workspace
    
    # Interactive mode for development
    stdin_open: true
    tty: true
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Networks
networks:
  opencode-network:
    driver: bridge
    name: horizon-opencode-network

# Volumes (for persistent data if needed)
volumes:
  # Uncomment if using additional services
  # postgres_data:
  #   driver: local
  
  # OpenCode data volume (alternative to bind mount)
  opencode_data:
    driver: local
    name: horizon-opencode-data
  
  # AI assets volume (alternative to bind mount)
  ai_assets:
    driver: local
    name: horizon-ai-assets

